name: Unit Testing

on:
  push:
  pull_request:

jobs:
  unit_testing:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [14, 15, 16, 17]
        os: [ubuntu-20.04, ubuntu-18.04, macos-11, macos-10.15]
    steps:
      - uses: actions/checkout@v2
        name: Checkout repository
      - uses: actions/setup-node@v2
        name: Setup node
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
      - run: npm run lint
        name: Lint test
      - run: npm run test
        name: Unit testing
